#My First GithubAction

#Name of the workflow
name: Hello

#Trigger that will run the workflow

on:
  workflow_dispatch:
             


#What the workflow will do
jobs:
#Name of the job
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: checkput code
        uses: actions/checkout@v4

      - name: Say Hello to users
        run: echo "Hello users"

      - name: Say Hellow to logged in users
        run: echo "Hello current user $USER"
      
      - name: Print current date
        run: date

      - name: List files in the repository
        run: |
            ls -R ${{ github.workspace }}

      - name: Runner's opearting system
        run: cat /etc/os-release

      - name: Print branch name
        run: |
          echo "Current branch: ${GITHUB_REF##*/}"